name = "lustre_pipes"
version = "0.0.1"
gleam = ">= 1.4.0"

description = "Write Lustre template using Gleam's pipes"

licences = ["MIT"]
repository = { type = "github", user = "weedonandscott", repo = "lustre_pipes" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
